student_app/urls.py
from django.urls import path
from . import views

app_name = 'student_app'

urlpatterns = [
  path('', views.index, name='index'),
  path('student/<int:student_id>/', views.details, name='student'),

]

student_project/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('student_app.urls'))
]

student_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
	prenom=models.CharField(max_length=20)
	nom=models.CharField(max_length=20)
	date=models.DateField()

	def __str__(self):
		return self.prenom

class Note(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	matiere=models.CharField(max_length=20)
	note=models.IntegerField(default=0)
	coefficient=models.IntegerField(default=0)

	def __str__(self):
		return self.matiere

student_app/views.py
from django.shortcuts import render, get_object_or_404
from student_app.models import Student , Note

# Create your views here.
def index(request):
	students=Student.objects.all().order_by('id')
	return render(request, 'students/index.html', context={ 'students': students})

def details(request,student_id):
	student=Student.objects.get(id=student_id)
	note=Note.objects.filter(student=student)
	print(note)
	return render(request, 'students/details.html', context={ 'student': student ,'note':note})

student_app/templates/students/details.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Profile of {{ blogger.first_name }}</title>
</head>
<body>

  <h1>Note De L'Eleve</h1>
  <table class="table">
  <thead>
      <tbody>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Prenom</th>
          <th scope="col">Nom</th>
          <th scope="col"> Date De Naissance</th>
        </tr>
      </tbody>
    <tbody>
          <tr>
            <th> {{student.id}}</th>
            <th scope="row">{{student.nom}}</th>
            <td>  {{student.prenom }} </td>
            <td>  {{student.date }} </td>

          </tr>
    </tbody>
        <tbody>
          <tr>
            <th scope="col">ID#</th>
            <th scope="col">Matiere</th>
            <th scope="col">Note</th>
            <th scope="col"> Coefficient</th>
          </tr>
        </tbody>
        <tbody>
          {% for notes in note %}
          <tr>
            <td scope="row">{{notes.id}}</td>
            <td>{{notes.matiere}}</td>
            <td>  {{notes.note }} </td>
            <td>  {{notes.coefficient }} </td>
          </tr>
          {% endfor %}
        </tbody
          
   

  </thead>

student_app/templates/students/index.html
<!DOCTYPE html>
<html>
<head>
	 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<title>Liste des Etudiants</title>
</head>
<body>
	<h1>Liste Des Etudiants</h1>
	<table class="table">
	<thead>
		<tr>
	  		
      		<th scope="col">Prenom</th>
      		<th scope="col">Nom</th>

      		
		</tr>
	</thead>
	<div> 
		
		{% for student in students %}
			<tbody>
    			<tr>
    			  <th scope="row">{{student.nom}}</th>
    			  <td><a href="{% url 'student_app:student' student.id %}">{{student.prenom }} </a></td>
    			</tr>
		{% endfor %}

	</div>

</body>
</html>